# Parameters for the mini_bot_node
mini_bot_node:
  ros__parameters:
    wheel_radius: 0.0325
    wheel_base: 0.1
    dt: 0.05
    serial_port: "/dev/ttyACM0"
    pulses_window: 5
    pulses_per_revolution: 20

# Parameters for the navigation_node
navigation_node:
  ros__parameters:
    wheel_radius: 0.0325
    wheel_base: 0.1
    dt: 0.05
    use_external_theta: False

# Parameters for the controller_node
controller_node:
  ros__parameters:
    wheel_radius: 0.0325
    wheel_base: 0.1
    dt: 0.05
    max_delta_pwm: 25.0
    v_pid:
      kp: 1.0
      ki: 0.1
      kd: 0.05
      integral_max: 0.2
    w_pid:
      kp: 1.0
      ki: 0.1
      kd: 0.05
      integral_max: 0.2
    # The LUT is now a flat list, which will be reshaped in the node
    velocity_to_pwm_lut_left:
      - -15.0
      - -255.0
      - -10.0
      - -180.0
      - -5.0
      - -100.0
      - -1.0
      - -30.0
      - 0.0
      - 0.0
      - 1.0
      - 30.0
      - 5.0
      - 100.0
      - 10.0
      - 180.0
      - 15.0
      - 255.0
    velocity_to_pwm_lut_right:
      - -15.0
      - -255.0
      - -10.0
      - -180.0
      - -5.0
      - -100.0
      - -1.0
      - -30.0
      - 0.0
      - 0.0
      - 1.0
      - 30.0
      - 5.0
      - 100.0
      - 10.0
      - 180.0
      - 15.0
      - 255.0
