# Parameters for the mini_bot_node
mini_bot_node:
  ros__parameters:
    wheel_radius: 0.0325
    wheel_base: 0.15
    dt: 0.05
    serial_port: "/dev/ttyACM0"
    pulses_window: 5
    pulses_per_revolution: 20

# Parameters for the navigation_node
navigation_node:
  ros__parameters:
    wheel_radius: 0.0325
    wheel_base: 0.15
    dt: 0.05
    use_external_theta: False

# Parameters for the controller_node
controller_node:
  ros__parameters:
    max_v: 0.2  #m/s
    max_w: 1.57 #rad/s
    wheel_radius: 0.0325
    wheel_base: 0.15
    dt: 0.1
    max_delta_pwm: 25.0
    v_pid:
      kp: 0.0
      ki: 0.0
      kd: 0.0
      integral_max: 0.1
    w_pid:
      kp: 1.5
      ki: 0.0
      kd: 0.2
      integral_max: 0.1
    # The LUT is now a flat list, which will be reshaped in the node
    velocity_to_pwm_lut_left:
      - -6.0
      - -255.0
      - -3.0
      - -225.0
      - -2.0
      - -200.0
      - -1.0
      - -100.0
      - 0.0
      - 0.0
      - 1.0
      - 100.0
      - 2.5
      - 200.0
      - 3.7
      - 225.0
      - 7.0
      - 255.0
    velocity_to_pwm_lut_right:
      - -6.0
      - -255.0
      - -3.0
      - -225.0
      - -2.0
      - -200.0
      - -1.0
      - -100.0
      - 0.0
      - 0.0
      - 1.0
      - 100.0
      - 2.5
      - 200.0
      - 3.7
      - 225.0
      - 7.0
      - 255.0
